services:
  # Servicio MongoDB
  mongo:
    image: mongo
    container_name: mongo-srv
    networks:
      - tpf
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db
      - ./backups:/backups

  # Servicio Frontend
  frontend:
    build:
      context: ./tpf-frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - tpf

  # Servicio Backend
  backend:
    build:
      context: ./tpf-backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo/tpf
    networks:
      - tpf

networks:
  tpf:

volumes:
  mongo-data: