services:
  # Servicio MongoDB
  mongo:
    image: mongo
    container_name: mongo-srv
    networks:
      - tpf
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db

  # Cliente para MongoDB
  mongo-express:
    image: mongo-express
    container_name: mongo-cli
    networks:
      - tpf
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-srv

  # Servicio de backups automatizados
  mongo-backup:
    image: mongo
    container_name: mongo-backup
    depends_on:
      - mongo
    volumes:
      - ./backups:/backups
    entrypoint: >
      /bin/sh -c "
      while true; do
        sleep 86400;  # Intervalo de 24 horas
        mongodump --host mongo-srv --out /backups/backup-$(date +'%Y%m%d%H%M%S');
      done"
    networks:
      - tpf

  # Servicio Frontend
  frontend:
    build:
      context: ./tpf-frontend
    container_name: frontend-app
    ports:
      - "4200:4200" # Exponer el puerto del frontend
    networks:
      - tpf

  # Servicio Backend
  backend:
    build:
      context: ./tpf-backend
    container_name: backend-app
    ports:
      - "3000:3000" # Exponer el puerto del backend
    depends_on:
      - mongo # Asegurar que MongoDB esté disponible
    environment:
      MONGO_URI: mongodb://mongo/tpf
    networks:
      - tpf

networks:
  tpf:

volumes:
  mongo-data:
