# Imagen base para Node.js
FROM node:18

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias del backend
RUN npm install

# Copia todo el código fuente al contenedor
COPY . .

# Expone el puerto del backend
EXPOSE 3000

# Comando para iniciar el servidor en modo desarrollo
CMD ["npm", "start"]