name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Clona el repositorio
    - name: Checkout source code
      uses: actions/checkout@v3

    # Configura Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Logueo en DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construcción de imágenes
    - name: Build and push backend image
      run: |
        docker build -t marianella/backend:latest ./tpf-backend
        docker push marianella/backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t marianella/frontend:latest ./tpf-frontend
        docker push marianella/frontend:latest
    
    # Instalar Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version     

    # Ejecuta la aplicación localmente
    - name: Deploy locally
      run: |
        docker-compose down
        docker-compose pull
        docker-compose up -d --build
